changelog:
  categories:
    - title: Framework
      labels:
        - framework
    - title: Generator
      labels:
        - generator
    - title: Templates
      labels:
        - templates
    - title: Maintenance
      labels:
        - maintenance
