disabled_rules:
- anonymous_argument_in_multiline_closure
- conditional_returns_on_newline
- explicit_self
- extension_access_modifier
- file_types_order
- function_default_parameter_at_end
- indentation_width
- missing_docs
- multiline_arguments_brackets
- nslocalizedstring_require_bundle
- prefixed_toplevel_constant
- raw_value_for_camel_cased_codable_enum
- redundant_string_enum_value
- required_deinit
- vertical_whitespace_between_cases
- vertical_whitespace_opening_braces
