name: Bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_${{ secrets.XCODE_VERSION }}.app/Contents/Developer

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bazelisk build //:Nodes
