name: Bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  bazel:
    name: Bazel
    runs-on: macos-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Build
      run: bazelisk build //:Nodes
