name: DocC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  docc:
    name: DocC
    runs-on: macos-12
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Build documentation
      run: make docs open="no" DERIVED_DATA_PATH="$(mktemp -d)"
