name: DocC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_${{ secrets.XCODE_VERSION }}.app/Contents/Developer

jobs:
  docc:
    name: DocC
    runs-on: macos-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build Documentation
      run: xcodebuild docbuild -scheme "Nodes" -destination "generic/platform=iOS"
