name: DocC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_${{ secrets.XCODE_VERSION }}.app/Contents/Developer

jobs:
  docc:
    name: DocC
    runs-on: macos-12
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
    - name: Add ssh key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
        ssh-add - <<< "${{ secrets.TINDER_GITHUB_SSH_KEY }}"
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build Documentation
      run: xcodebuild docbuild -scheme "Nodes" -destination "generic/platform=iOS"
