name: Genesis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  genesis:
    name: Genesis
    runs-on: macos-13
    env:
      SIMULATOR: iPhone 14
    steps:
    - name: Install dependencies
      run: |
        brew install mint xcodegen needle mockolo
        mint install yonaskolb/genesis
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Create temporary directory
      run: mkdir QuickStart
    - name: Generate project files
      working-directory: QuickStart
      run: >
        git config user.name 'Test User';
        mint run genesis generate "${{ github.workspace }}/genesis.yml" --options
        "nodes:0.0.0, project:QuickStart, prefix:com.tinder, author:$(git config user.name), date:$(date +"%-m/%-d/%y"), path:${{ github.workspace }}"
    - name: Generate Xcode project
      working-directory: QuickStart
      run: xcodegen
    - name: Resolve Swift package
      working-directory: QuickStart
      run: swift package resolve
    - name: Resolve package dependencies
      working-directory: QuickStart
      run: xcodebuild -resolvePackageDependencies
    - name: Run SwiftLint
      working-directory: QuickStart
      run: $(find ".build/artifacts/quickstart" -type f -name swiftlint -perm +111 -print -quit) --strict
    - name: Build
      working-directory: QuickStart
      run: xcodebuild build-for-testing -scheme "QuickStart" -destination "name=$SIMULATOR,OS=latest"
    - name: Run tests
      working-directory: QuickStart
      run: xcodebuild test-without-building -scheme "QuickStart" -destination "name=$SIMULATOR,OS=latest"
